-- MySQL / MariaDB
CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(128) NOT NULL PRIMARY KEY,
    data TEXT NOT NULL,
    ip VARCHAR(45) NOT NULL DEFAULT '',
    agent VARCHAR(5000) NOT NULL DEFAULT '',
    stamp INT UNSIGNED NOT NULL DEFAULT 0,
    INDEX idx_stamp (stamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
